### PR TITLE
fix: user profile interest pill UI fix

### LINKED ISSUE #887: Bug: Profile UI is broken on beta for interest
### Describe the bug

Screen Shot 2023-02-20 at 9 16 31 AM

### Steps to reproduce

View https://deploy-preview-881--oss-insights.netlify.app/user/bdougie 

### Affected services

insights.opensauced.pizza

### Platforms

_No response_

### Browsers

_No response_

### Environment

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR fixes the profile interest pills breaking

## Related Tickets & Documents
Fixes #887

### Before
image

### After
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/molecules/ContributorProfileInfo/contributor-profile-info.tsx [hunk 1]
```diff
@@ -69,16 +69,25 @@ const ContributorProfileInfo = ({
                 "I am an open source developer with a passion for music and video games. I strive to improve the open source community and am always looking for new ways to contribute."}
             </p>
             <div className="flex flex-col text-sm mt-2 text-light-slate-9 gap-2">
-              {displayLocalTime && <span className="flex gap-2 items-center">
-                <FiClock className="text-light-slate-9" /> Local time: 12:32 PM
-              </span>}
+              {displayLocalTime && (
+                <span className="flex gap-2 items-center">
+                  <FiClock className="text-light-slate-9" /> Local time: 12:32 PM
```
Comment (bdougie) [inline components/molecules/ContributorProfileInfo/contributor-profile-info.tsx:74]:
```suggestion
                  <FiClock className="text-light-slate-9" /> Local time: 12:32 PM
```
weird that this is still hardcoded 😅 - are you able to fix or hide this?

**Review by bdougie — APPROVED** [review]
Added a comment on some thing unrelated. Can you fix that or open an issue to fix that.

File: components/molecules/ContributorProfileInfo/contributor-profile-info.tsx (hunk 1 above)
Comment (OgDev-01) [reply components/molecules/ContributorProfileInfo/contributor-profile-info.tsx]: Pushed a fix

File: components/molecules/ContributorProfileInfo/contributor-profile-info.tsx [hunk 2]
```diff
@@ -69,16 +69,26 @@ const ContributorProfileInfo = ({
                 "I am an open source developer with a passion for music and video games. I strive to improve the open source community and am always looking for new ways to contribute."}
             </p>
             <div className="flex flex-col text-sm mt-2 text-light-slate-9 gap-2">
-              {displayLocalTime && <span className="flex gap-2 items-center">
-                <FiClock className="text-light-slate-9" /> Local time: 12:32 PM
-              </span>}
+              {displayLocalTime && (
+                <span className="flex gap-2 items-center">
+                  <FiClock className="text-light-slate-9" /> Local time:
+                  <span> {getTimeByTimezone(timezone ? getTimezone(timezone) : 1)}</span>
```
Comment (bdougie) [inline components/molecules/ContributorProfileInfo/contributor-profile-info.tsx:75]:
```suggestion
                  <span> {getTimeByTimezone(timezone ? getTimezone(timezone) : 1)}</span>
```

Why `: 1`

Comment (bdougie) [reply components/molecules/ContributorProfileInfo/contributor-profile-info.tsx:75]: nvm, I looked at the code 😅. I think its better than nothing, but we probably want to UTC with no offset be the default or show nothing at all. But since is scope creep, i'd rather merge and move on.
