### PR TITLE
fix: Feed page responsiveness 

### LINKED ISSUE #1336: Bug: General Responsiveness of the Highlights Page
### Describe the bug

General Responsiveness on the Highlights Page Isn't Crisp, some content goes out of the viewport and certain width size and some overflow on the x-axis is scrolled at some point too

screencast-insights opensauced pizza-2023 07 07-00_18_44

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/feed
2. Restore you browser and reduce the width size to the smallest possible
3. Pay attention to how the viewport treats the content

### Browsers

Chrome

### Additional context (Is this in dev or production?)

Dev and Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### LINKED ISSUE #1453: Bug: Feed Page is not responsive
### Describe the bug

https://github.com/open-sauced/insights/assets/62995161/41e11c94-257f-40ee-8955-2e00d10cc036

### Steps to reproduce

Go to https://insights.opensauced.pizza/feed

Resize your browser to check responsiveness.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by RitaDee**
## Description

Fixes #1453

Fixes #1336 

**Duplicate to Issue https://github.com/open-sauced/insights/issues/1336**

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
#1336

## Mobile & Desktop Screenshots/Recordings

Before:

[](https://github.com/open-sauced/insights/assets/62995161/41e11c94-257f-40ee-8955-2e00d10cc036)

After:

https://github.com/open-sauced/insights/assets/106407013/11f56cc8-4cbf-4d8d-bb66-02f42044dc36

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by babblebey** [comment]
Reviewing this @RitaDee, in the meantime do append the `Fixes` term to the duplicate issue too so It can allow it automatically close on merge this PR.

**Comment by RitaDee** [comment]
@babblebey Done.

**Review by babblebey — COMMENTED** [review]
Great stuff @RitaDee, but your implementation isn't quite there yet... I have made the diagram below to guide you, it suggests some classes you should remove and ones to add...

screenshot-miro com-2023 08 05-13_45_03

### Tasks

- Append the `container` and `px-2 md:px-16` classes to the `main` element i.e. the first purple area in the diagram
- Append/update the stated classes and remove the striked ones from the next nested `div`.
- Do the same for the other `div`s. 
- Remove all fixed width from the `Left (userCard) div` and `Right (filter) div` children `div`s replacing them with `w-full` to allow them inherit width from their respective parent `div`s.

### Expected Behaviour

- The Central (feedInput form and feeds) `div` should have a flexible width, taking all available spaces in the center
- The Left (userCard) `div` should take `24%` width of the total viewport initially, but when screen size scales down below `1280px` i.e. tailwind `xl`, its display should be `none`.
- The Right (filter) `div` should also take `24%` width of the total viewport initially, but when screen size scales down below `1280px` i.e. tailwind `xl`, its width should increase to `30%`, at thesame point when the `Left (userCard) div` is no longer in display. 
- When screen size scales down below `1024px` i.e. tailwind `lg` the `Right (filter) div` display at this point should also be `none` leaving on the `Central (feedInput form and feeds) div`.

### Potential Bottlenecks

**Review by bdougie — CHANGES_REQUESTED** [review]
I noticed some of the things @babblebey mentioned. Marking requested changes for other reviewers.

**Comment by RitaDee** [comment]
Thank you, @babblebey for providing the diagram and the specific tasks to make the /feed page responsive. I have carefully reviewed the requirements, and I'll make the necessary changes as suggested.

**Comment by RitaDee** [comment]
I acknowledge the suggestions provided by @babblebey. Thank you

### Update: 
I have improved the layout and styles of the /feed page to achieve a responsive design as outlined in the tasks provided. The changes focus on the main, left, and right sections, ensuring they adapt gracefully to different screen sizes.

I applied the container and px-2 md:px-16 classes to the main element, allowing proper padding and responsiveness. Also, used the appropriate tailwind class to achieve this.

### Current behaviour:





https://github.com/open-sauced/insights/assets/106407013/25935c04-3d45-400b-b291-ce6ef0522101

**Review by bdougie — APPROVED** [review]
Thanks

File: layouts/profile.tsx [hunk 1]
```diff
@@ -8,7 +8,9 @@ const ProfileLayout = ({ children }: { children: React.ReactNode }) => {
     <div className="flex flex-col min-h-screen">
       <TopNav />
       <div className="page-container flex grow flex-col items-center">
-        <main className="flex pb-16 w-full flex-1 flex-col items-center bg-light-slate-2">{children}</main>
+        <main className="container px-2 flex md:px-16 pb-16 w-full flex-1 flex-col items-center bg-light-slate-2">
```
Comment (babblebey) [inline layouts/profile.tsx:11]: ### REGRESSION!!!

I see that the changes to the `main` occured in the `ProfileLayout` component, this will lead to Regression in other components where the `ProfileLayout` is integrated. See pages/component where regression occurs below with screenshots

- The `/user/[username]` page integrates the `ProfileLayout` and it as regressed: https://deploy-preview-1490--oss-insights.netlify.app/user/babblebey/highlights

image

- The `/user/setting` page is the second component that integrates the `ProfileLayout` and it as also regressed: https://deploy-preview-1490--oss-insights.netlify.app/user/settings

image

This is due to the classes (`container`, `px-2` and `md:px-16`) that we moved up into the component.

### FIX!!

```suggestion
        <main className="flex pb-16 w-full flex-1 flex-col items-center bg-light-slate-2">
```

We will have to remove the classes (`container`, `px-2` and `md:px-16`), from there moving it back to its initial place in the child `div`.

File: pages/feed/index.tsx [hunk 2]
```diff
@@ -126,13 +126,10 @@ const Feeds: WithPageLayout<HighlightSSRProps> = (props: HighlightSSRProps) => {
         image={ogImage}
         twitterCard="summary_large_image"
       />
-      <div
-        className="container flex flex-col gap-16 px-2 pt-12 mx-auto md:px-16 lg:justify-end md:flex-row"
-        ref={topRef}
-      >
-        <div className="flex-col flex-1 hidden gap-6 mt-12 md:flex">
+      <div className="w-full gap-[2rem] justify-center flex flex-col md:gap-6 xl:gap-16 pt-12 md:flex-row" ref={topRef}>
+        <div className="flex-col flex-1 xl:flex hidden gap-6 mt-12">
```
Comment (babblebey) [inline pages/feed/index.tsx:130]:
```suggestion
        <div className="w-[24%] flex-col flex-none xl:flex hidden gap-6 mt-12">
```

You are missing a `width` and `flex-none` from the `Left (userCard) div`.

With `flex-none`, the goal is to size the `Left (userCard) div` according to the `width` (that you will have to set to `24%`), rendering it fully inflexible: so it neither shrinks nor grows in relation to its parent flex container.

File: pages/feed/index.tsx [hunk 3]
```diff
@@ -284,7 +281,7 @@ const Feeds: WithPageLayout<HighlightSSRProps> = (props: HighlightSSRProps) => {
             <FollowingHighlightWrapper selectedFilter={selectedRepo} emojis={emojis} />
           </TabsContent>
         </Tabs>
-        <div className="hidden gap-6 mt-10 md:flex-1 md:flex md:flex-col">
+        <div className="md:hidden gap-6 mt-10 md:flex-1 lg:flex md:flex-col">
```
Comment (babblebey) [inline pages/feed/index.tsx:284]:
```suggestion
        <div className="md:hidden gap-6 mt-10 w-[30%] lg:w-[24%] flex-none lg:flex md:flex-col">
```

You are also missing a responsive `width` and `flex-none` from the `Right (Filter) Div`. _for the same reason as `Left (userCard) div`_.

...and 

```suggestion
        <div className="hidden gap-6 mt-10 md:flex-1 lg:flex flex-col">
```

Tailwind uses a mobile-first breakpoint system.

This means that unprefixed classes (like `hidden`) take effect on all screen sizes, while prefixed one (like `lg:flex`) only take effect at the specified breakpoint (`lg` in this case) and above.

So `Right Filter Div` will be `hidden` normally on all screen sizes and it will only be in display again at `lg` (desktop) and above i.e. `lg:flex`.

So you needn't specify a responsive class of `md:hidden` since its gonna be hidden normally till `lg`.

File: pages/feed/index.tsx [hunk 4]
```diff
@@ -126,13 +126,10 @@ const Feeds: WithPageLayout<HighlightSSRProps> = (props: HighlightSSRProps) => {
         image={ogImage}
         twitterCard="summary_large_image"
       />
-      <div
-        className="container flex flex-col gap-16 px-2 pt-12 mx-auto md:px-16 lg:justify-end md:flex-row"
-        ref={topRef}
-      >
-        <div className="flex-col flex-1 hidden gap-6 mt-12 md:flex">
+      <div className="w-full gap-[2rem] justify-center flex flex-col md:gap-6 xl:gap-16 pt-12 md:flex-row" ref={topRef}>
```
Comment (babblebey) [inline pages/feed/index.tsx:129]:
```suggestion
      <div className="w-full gap-[2rem] justify-center flex flex-col pt-12 md:flex-row" ref={topRef}>
```

The responsive/prefixed `gap` classes are not affecting anything at those breakpoints (i.e. `xl` and `md`), because the flex items the points are already reduced leaving the `gap` with nothing to space out.

So we can remove them.

File: components/atoms/UserCard/user-card.tsx [hunk 5]
```diff
@@ -18,13 +18,13 @@ const UserCard = ({ username, name, meta, loading }: UserCardProps) => {
   const avatarUrl = getAvatarByUsername(username);
 
   return (
-    <div className="w-full pb-6 border rounded-lg bg-light-slate-1 border-zinc-200">
+    <div className="pb-6 border bg-light-slate-1 w-max rounded-xl border-zinc-200">
```
Comment (babblebey) [inline components/atoms/UserCard/user-card.tsx:21]:
```suggestion
    <div className="pb-6 border bg-light-slate-1 w-full rounded-lg border-zinc-200">
```

Return the full width for the `user-card` and the `border-radius` component.

#### Why though!?

- The width `w-full` for size inheritance reason
- The Border radius `rounded-lg` for uniformity reason, looking at all other sibling components/divs on the `Right (Filter) Div` and `Left (userCard) div`.

File: components/atoms/UserCard/user-card.tsx [hunk 6]
```diff
@@ -18,13 +18,13 @@ const UserCard = ({ username, name, meta, loading }: UserCardProps) => {
...
       {loading ? (
         <div className="flex items-center justify-center h-32 w-72">
           <Spinner className="mt-6 " />
         </div>
       ) : (
-        <div className="flex flex-col items-center gap-6 px-6 ">
+        <div className="flex flex-col items-center gap-6 px-9">
```
Comment (babblebey) [inline components/atoms/UserCard/user-card.tsx:27]: I'm very curious to know why you thought to increase this padding!?

**Review by babblebey — COMMENTED** [review]
Great work hey @RitaDee,

We have some few things to address.
