### PR TITLE
fix: on page reload Insights page redirecting to Dashboard

### LINKED ISSUE #1503: Bug: middleware odd behaviour
### Describe the bug

If you update the page when you are on the insight page the middleware will send you again to the dashbaord. 

https://github.com/open-sauced/insights/assets/18273833/857ac609-8b91-4bab-a6a1-fbbd9cf7b147

### Steps to reproduce

1. go to https://insights.opensauced.pizza/hub/insights
2. refresh the page when you are on the page
3. you will find yourself on the dashbaord

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by deepakrudrapaul**
## Description

This PR fixes the Insights page redirecting to Dashboard on page reload.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1503 

## Mobile & Desktop Screenshots/Recordings

Before :
before

After :
after

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
:smiley:

### CODE REVIEW

File: layouts/private-wrapper.tsx [hunk 1]
```diff
@@ -11,12 +11,13 @@ interface PrivateWrapperProps {
...
   const user = useUser();
   const router = useRouter();
+  const { isLoading } = useSessionContext();
   const { session: isValid } = useSession(true);
 
   async function checkSession() {
     if (router.asPath?.includes("login")) return;
 
-    if (!isValid) {
+    if (!isValid && !isLoading) {
```
Comment (brandonroberts) [inline layouts/private-wrapper.tsx:20]: Does this need to be in the `useEffect` deps array also?

Comment (deepakrudrapaul) [reply layouts/private-wrapper.tsx:20]: Yes, it would be beneficial to include it in the `useEffect` dependencies array to ensure the effect behaves as expected. Thank you for considering this!

**Review by bdougie — APPROVED** [review]

**Review by NsdHSO — APPROVED** [review]
LGTM

**Review by brandonroberts — APPROVED** [review]
