### PR TITLE
feat: handle close modal when click outside and fix accessibility issues

### LINKED ISSUE #689: feature: close select limit modal when the outside is clicked
### Type of feature

🍕 Feature

### Current behavior

Currently, when the button `Showing: 10 per page` is clicked, it shows different options to choose.
When clicking outside of that select options (or modal), it doesn't close it unless an option is selected or the button is clicked again.

select

### Suggested solution

Adding an event listener to check if the menu is open and the clicked target is not within the menu.
Here is an example of integration: https://github.com/open-sauced/insights/blob/c7430d7265b5654e8ef65a83b1877f8a16bb7ac7/components/molecules/SuperlativeSelector/superlative-selector.tsx#L26-L47

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by TAKANOME-DEV**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR fixes the issue with the Select component which is when you click outside the dropdown, it doesn't close. And also some accessibility issues.
## Related Tickets & Documents

Fixes #689 and probably #358 

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by TAKANOME-DEV** [comment]
For the mobile view, maybe we should move the select at the top?
responsive

**Comment by bdougie** [comment]
> For the mobile view, maybe we should move the select at the top? responsive

That can be discussed on a new issue to avoid scope creep on this. 

Also noticing the UI is change in the deploy preview. There are now Not ideal

now:
Screen Shot 2022-12-22 at 12 04 33 PM

before:
Screen Shot 2022-12-22 at 12 06 05 PM

**Comment by bdougie** [comment]
There might be a better solution we can borrow from the hot repo - https://github.com/open-sauced/hot/pull/319

**Comment by TAKANOME-DEV** [comment]
> Also noticing the UI is change in the deploy preview. There are now Not ideal
> 
> now on preview: https://deploy-preview-705--oss-insights.netlify.app/javascript/repositories/filter/recent Screen Shot 2022-12-22 at 12 04 33 PM
> 
> live on production: https://insights.opensauced.pizza/javascript/repositories/filter/recent Screen Shot 2022-12-22 at 12 06 05 PM
> 
This deploy preview is from my first commit, I think the last commit is not yet deployed :rocket:

> What is your setup, operating system and browser @TAKANOME-DEV?
>
```sh
❯ neofetch
            .-/+oossssoo+/-.               takanome_dev@Ubuntu-22 
        `:+ssssssssssssssssss+:`           ---------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.1 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: 24791Q6 ThinkPad L530 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.15.0-56-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 2 hours, 53 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2378 (dpkg), 10 (flatpak), 11 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.8.1 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1366x768 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Unity 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: WhiteSur-Dark-blue 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: WhiteSur-Dark-solid [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: WhiteSur-dark [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: Tabby 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i5-3230M (4) @ 3.200GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel 3rd Gen Core processor Graphics Controller 
      -+sssssssssssssssssyyyssss+-         Memory: 4474MiB / 5760MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       
                                                                   
Browser: Brave v1.46.144
```

**Comment by bdougie** [comment]
Need to opt you in so your commits auto deploy.

File: components/atoms/Select/custom-select.tsx [hunk 1]
```diff
@@ -10,72 +14,59 @@ interface SelectProps {
...
-          readOnly
-          type="text"
-          className="overflow-scroll text-sm cursor-pointer text-light-slate-12 focus:outline-none bg-transparent"
-        />
-        <div className="w-6 h-4 relative overflow-hidden">
-          {" "}
-          <RiArrowUpSLine className="absolute bottom-1" /> <RiArrowDownSLine className="absolute top-1  " />
-        </div>
+    <Select.Root>
+      <div className={clsx("relative bg-white cursor-pointer focus:border-light-orange-9 focus:ring focus:ring-light-orange-9 items-center overflow-x-hidden rounded-lg text-base text-light-slate-10 min-w-min", className ? className : "")}>
```
Comment (SunGoldTech) [inline components/atoms/Select/custom-select.tsx:27]: nit: not a blocker but a suggestion:
use the `||` operator instead of the ternary `?`
```suggestion
      <div className={clsx("relative bg-white cursor-pointer focus:border-light-orange-9 focus:ring focus:ring-light-orange-9 items-center overflow-x-hidden rounded-lg text-base text-light-slate-10 min-w-min", className || "")}>
```

**Review by SunGoldTech — APPROVED** [review]
LGTM 🍕

**Review by bdougie — CHANGES_REQUESTED** [review]
Functionally this works. I can't approve as-is due to the style changes. I am on Chrome

Deploy Preview
Screen Shot 2022-12-23 at 5 33 36 AM

Production
Screen Shot 2022-12-23 at 5 33 30 AM

I need to match the original design. Please let me know if you have any questions or blocked on anything.

**Comment by TAKANOME-DEV** [comment]
> I need to match the original design. Please let me know if you have any questions or blocked on anything.
>
Sure, what about the check icon?

crop

**Comment by bdougie** [comment]
No check.

**Comment by TAKANOME-DEV** [comment]
> Screen Shot 2022-12-23 at 5 33 30 AM
> 
Note that the items are bold. I tried to do it, but it does not work  (even with `!important`). Probably because of #569

**Comment by bdougie** [comment]
I think it still needs to be left aligned. The Red line shows where it should be. 


Screen Shot 2022-12-27 at 12 05 43 PM

File: components/atoms/Select/custom-select.tsx [hunk 2]
```diff
@@ -10,72 +13,55 @@ interface SelectProps {
...
+          <Select.Content
+            className={clsx("absolute right-0 top-9 bg-white overflow-hidden rounded-lg border shadow-superlative", label ? "-left-17" : "left-0")}
+          >
+            <Select.Viewport>
+              {options ?
+                options.map((option) => (
+                  <Select.Item
+                    key={option.name}
+                    className="custom-select__select-item flex items-center text-sm text-light-slate-12 cursor-pointer relative px-4 py-2 md:py-1 rounded-md outline-none"
+                    value={option.name}
```
Comment (brandonroberts) [inline components/atoms/Select/custom-select.tsx:52]: We should be using the `value` here instead of the `name`

File: components/atoms/Select/custom-select.tsx [hunk 3]
```diff
@@ -10,72 +13,55 @@ interface SelectProps {
...
-  const handleToggle = () => {
-    setIsOpen(!isOpen);
-  };
-  const handleSelected = (option: { name: string; value: any }) => {
-    const { name, value } = option;
-    setSelected((prev) => ({ ...prev, name, value }));
-    onChange?.(value);
-    setIsOpen(false);
+  const handleSelected = (value: string) => {
+    const selected = Number(value.substring(0, 2));
```
Comment (brandonroberts) [inline components/atoms/Select/custom-select.tsx:24]: We should be using the actual value instead of a substring of the name. The `options` should provide an array of name/value objects

```js
[
  { name: '10 per page', value: 10 }
]
```

**Review by brandonroberts — CHANGES_REQUESTED** [review]

File: styles/globals.css [hunk 4]
```diff
@@ -40,3 +40,19 @@ input[type="search"]::-webkit-search-cancel-button {
 .z-50 {
   z-index: 50;
 }
+
+.-left-17 {
```
Comment (0-vortex) [inline styles/globals.css:44]: remove this please, relative positioning and margins will solve this problem

File: styles/globals.css [hunk 5]
```diff
@@ -40,3 +40,19 @@ input[type="search"]::-webkit-search-cancel-button {
...
+  left: -4.4rem;
+}
+
+.custom-select__select-item[data-highlighted] {
```
Comment (0-vortex) [inline styles/globals.css:48]: please remove these lines and use the already existing https://github.com/ecklf/tailwindcss-radix plugin to set these classes. At the moment the plugin is configured with the default options, so reading the link should answer most questions, however, if you need advanced configuration, let us know and we can pair on this. Since the plugin is covering all the possible state classes, this should not be needed at all 🙉 🙈

**Review by 0-vortex — CHANGES_REQUESTED** [review]
Custom CSS classes need to be removed and radix state needs to be applied using existing patterns. 

Outside of that, LGTM! 👍

File: components/atoms/Select/custom-select.tsx (hunk 2 above)
Comment (TAKANOME-DEV) [reply components/atoms/Select/custom-select.tsx]: Nice catch :+1:

File: styles/globals.css (hunk 5 above)
Comment (TAKANOME-DEV) [reply styles/globals.css:48]: @0-vortex we don't have that plugin in this repo yet, I'm going to install it and test it out.

File: styles/globals.css (hunk 4 above)
Comment (TAKANOME-DEV) [reply styles/globals.css:44]: Even using relative positioning and margins, it won't align the dropdown.
IMO, defining a `left` or `margin` property with the value of  `-4.4rem` or using arbitrary values is the way to go.
@0-vortex what do you think about it?

File: styles/globals.css (hunk 5 above)
Comment (0-vortex) [reply styles/globals.css:48]: Oh really sorry about that too, thought we ported this over from hot.opensauced but apparently we didn't; that could explain some of the radix inconsistencies we were seeing that were generally magically solved by that plugin 😅

**Review by brandonroberts — APPROVED** [review]
LGTM

File: tailwind.config.js [hunk 6]
```diff
@@ -217,6 +217,7 @@ module.exports = {
       addVariant("child-hover", "& > *:hover");
```
Comment (0-vortex) [inline tailwind.config.js:217]: the variants can also be removed now that we have radix set-up again ❤️

File: styles/globals.css [hunk 7]
```diff
@@ -40,3 +40,7 @@ input[type="search"]::-webkit-search-cancel-button {
 .z-50 {
   z-index: 50;
 }
+
+.-left-18 {
```
Comment (0-vortex) [inline styles/globals.css:44]: remove this please

File: components/atoms/Select/custom-select.tsx [hunk 8]
```diff
@@ -10,72 +13,68 @@ interface SelectProps {
...
+          {label && <span className="inline-flex text-light-slate-9">{label}:</span>}
+          <Select.Value placeholder={placeholder} />
+          <Select.Icon className="w-4 h-4 relative overflow-hidden">
+            <RiArrowUpSLine className="absolute bottom-1" />
+            <RiArrowDownSLine className="absolute top-1" />
+          </Select.Icon>
+        </Select.Trigger>
+        <Select.Portal>
+          <Select.Content
+            className={clsx("absolute right-0 top-9 bg-white overflow-hidden rounded-lg border shadow-superlative", label ? "-left-18" : "left-0")}
```
Comment (0-vortex) [inline components/atoms/Select/custom-select.tsx:53]: change the classname to `className={clsx("right-0 bg-white overflow-hidden rounded-lg border shadow-superlative")}` to keep the select menu working natively

**Review by 0-vortex — CHANGES_REQUESTED** [review]
Following the suggested changes will unblock this PR both visually and code wise.

Following https://www.radix-ui.com/docs/primitives/components/select you can see the positioning is done all behind the scenes and doesn't need any patching. Because you properly positioned the parent items, the classes that were carried over worked and made an error - those classes were never needed however, and likely artifacts.

File: styles/globals.css (hunk 5 above)
Comment (TAKANOME-DEV) [reply styles/globals.css]: No problem :+1:

File: tailwind.config.js [hunk 9]
```diff
@@ -212,11 +212,6 @@ module.exports = {
     }
   },
   plugins: [
-    function ({ addVariant }) {
-      addVariant("child", "& > *");
-      addVariant("child-hover", "& > *:hover");
-      addVariant("child-active", "& > *:active");
-      addVariant("child-focus", "& > *:focus");
-    }
+    require("tailwindcss-radix")()
```
Comment (brandonroberts) [inline tailwind.config.js:215]: Does this change cause any visual changes anywhere else in the app?

Comment (TAKANOME-DEV) [reply tailwind.config.js:215]: I'm not really sure though, @0-vortex mentioned something like that -> https://github.com/open-sauced/insights/pull/705#discussion_r1058621830

**Comment by OgDev-01** [comment]
https://user-images.githubusercontent.com/62995161/210437395-86b03415-259d-4885-8341-7e035ee712f1.mov



https://user-images.githubusercontent.com/62995161/210437099-ea5af546-847e-4672-9a4f-e2d21c9bd6a6.mov

This behavior looks Strange, Is this a radix-related issue? @TAKANOME-DEV

**Comment by 0-vortex** [comment]
> Screen.Recording.2023-01-03.at.21.36.25.mov 
> 
>  Screen.Recording.2023-01-03.at.21.32.51.mov 
> 
> This behavior looks Strange, Is this a radix-related issue? @TAKANOME-DEV

The `select` component should not be CSS hacked to work as a drop-down. If a drop-down is required for that menu, the [dropdown](https://www.radix-ui.com/docs/primitives/components/dropdown-menu) should be used 😅

**Comment by TAKANOME-DEV** [comment]
> This behavior looks Strange, Is this a radix-related issue? @TAKANOME-DEV
>
I think that's how the select component works

File: tailwind.config.js (hunk 9 above)
Comment (0-vortex) [reply tailwind.config.js:215]: 👍

**Review by 0-vortex — APPROVED** [review]
