### PR TITLE
fix: corrected Alignment for mobile view

### LINKED ISSUE #1572: Feature: horizontally align toggle options on mobile
### Type of feature

🍕 Feature

### Suggested solution

solution

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by himanshumalviya15**
fix #1572

## Description
Corrected Alignment for mobile users 

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

### Before
image

### After
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
@himanshumalviya15 can you add a before and after image

**Comment by himanshumalviya15** [comment]
> @himanshumalviya15 can you add a before and after image

@bdougie Added please see

File: components/molecules/NivoScatterChart/nivo-scatter-chart.tsx [hunk 1]
```diff
@@ -142,7 +142,7 @@ const NivoScatterPlot = ({
           </>
         </ToggleGroup>
         {/* replaced display flex to hidden on show/bots container */}
-        <div className="flex flex-col gap-2 mt-3 md:mt-0 md:flex-row">
+        <div className="flex gap-2 mt-3 md:mt-0 flex-row">
```
Comment (takanome-dev) [inline components/molecules/NivoScatterChart/nivo-scatter-chart.tsx:145]: nit: We can omit `flex-row` since it's applied by default when using `flex`
```suggestion
        <div className="flex gap-2 mt-3 md:mt-0">
```

**Review by takanome-dev — COMMENTED** [review]
Let's remove the padding of the div container on mobile so the toggle switches can expand

| | |
| ------ | ------ |
|  |  |



```diff
- <div className="flex flex-col items-center justify-between pt-3 md:flex-row px-7">
+ <div className="flex flex-col items-center justify-between px-0 pt-3 md:flex-row md:px-7">

File: components/molecules/NivoScatterChart/nivo-scatter-chart.tsx (hunk 1 above)
Comment (himanshumalviya15) [reply components/molecules/NivoScatterChart/nivo-scatter-chart.tsx]: Resolved in latest commit, Thanks :)

**Comment by himanshumalviya15** [comment]
@bdougie I think we can merge this.

**Review by takanome-dev — APPROVED** [review]
🚀

**Review by NsdHSO — APPROVED** [review]
LGTM

**Review by brandonroberts — APPROVED** [review]
