### PR TITLE
fix: update generic profile page styles to match design

### LINKED ISSUE #692: Feature: Generic OpenSauced profile needs to match design
### Type of feature

🍕 Feature

### Current behavior

Current:

Screen Shot 2022-12-20 at 7 52 14 AM

### Suggested solution

Design:

image

### Additional context

@SunGoldTech can you assist in increasing the contribution calendar's width and height? https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=5206%3A5781&t=VyhaHubG5373bwBm-0

We also need to figure out how to get that roll up data in the element as well

Screen Shot 2022-12-20 at 7 58 01 AM

I don't think we will need to do "PRs reviewed"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by SunGoldTech**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR:

- creates a new `profile` layout component for the generic profile page
- updates the profile page to match UI design https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/OpenSauced-%E2%80%94-Insights-(insights.opensauced.pizza)?node-id=5206%3A5781&t=VyhaHubG5373bwBm-0

## Related Tickets & Documents
Fixes #692 

### Desktop
image

### Mobile
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/organisms/ContributorProfilePage/contributor-profile-page.tsx [hunk 1]
```diff
@@ -62,22 +62,22 @@ const ContributorProfilePage = ({
...
+        <div className="flex flex-col min-w-[270px] gap-4 ">
           <div className="pb-6 border-b">
             <Title className="!text-2xl !text-light-slate-12" level={3}>
               {githubName}
             </Title>
             <span className="text-light-slate-11 text-sm">{`@${githubName}`}</span>
           </div>
           <div>
-            <p className="mb-4 ">Language</p>
+            <p className="mb-4">Language</p>
```
Comment (bdougie) [inline components/organisms/ContributorProfilePage/contributor-profile-page.tsx:76]:
```suggestion
            <p className="mb-4">Languages</p>
```

**Review by bdougie — CHANGES_REQUESTED** [review]
Small typo fix.

**Review by bdougie — APPROVED** [review]
Just made a commit to fix the grammar.

**Review by brandonroberts — APPROVED** [review]
