### PR TITLE
fix: tab inconsistency in user profile matching the url

### LINKED ISSUE #1402: Bug: User profile highlights tab hides and stays active
### Describe the bug

When viewing the profile of a user that has not highlights. It still maintains the highlights tab as active when we visit `/user/{username}/highlights` even though the highlights tab is hidden. As a result the contributions tab is inactive and we have a blank screen in the tab
image

### Steps to reproduce

visit https://beta.insights.opensauced.pizza/user/Andarist/highlights

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR fixes the issue with tab inconsistency on the user profile page. Before now, when you visit a user profile with no highlights, the Highlights tab is active but hidden, leaving the contributors tab inactive but visible and blank. 

This PR fixes the issue by making the `hasHighlights` variable a state and updating the state with a `useMemo` hook to prevent unnecessary rerenders

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Fixes #1402

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/insights/assets/62995161/65e72666-5731-409a-af03-53ccfbbabc98

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]

File: components/organisms/ContributorProfileTab/contributor-profile-tab.tsx [hunk 1]
```diff
@@ -66,22 +66,28 @@ const ContributorProfileTab = ({
...
   const handleTabUrl = (tab: string) => {
     router.push(`/user/${login}/${tab.toLowerCase()}`);
   };
 
   useEffect(() => {
     setInputVisible(highlights && highlights.length !== 0 ? true : false);
     if (login && currentPathname) {
-      router.push(`/user/${login}/${currentPathname}`);
+      if (currentPathname === "highlights" && !hasHighlights) {
+        setCurrentPathname("contributions");
```
Comment (brandonroberts) [inline components/organisms/ContributorProfileTab/contributor-profile-tab.tsx:82]: Won't this create a rendering loop?

**Review by brandonroberts — CHANGES_REQUESTED** [review]

**Comment by OgDev-01** [comment]
> @OgDev-01 When I visit my profile that has highlights, I'm redirected to `contributions`
> 
> https://deploy-preview-1403--oss-insights.netlify.app/user/brandonroberts/highlights

This was happening because I didn’t update the `useEffect` dependency array with the appropriate dependencies. But i have done that now. I also made the `hasHighlight` state true by default.
