### PR TITLE
fix: properly format local time displayed on user's profile

### LINKED ISSUE #1275: Bug: user profile local time minute is not properly formatted
### Describe the bug

Screenshot_20230618-110920_Chrome

This should be `11:08am` instead

### Steps to reproduce

Visit a user profile when thier local time is minute value is not up in `tens`

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by codewithshariq**
"fix #1275"

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR fixes the issue related to local time formatting on the user's profile, the local time is properly formatted on the user's profile. If the minutes are less than 10, then a leading zero will be displayed and time will be properly displayed in 12 hours format.

## Related Tickets & Documents

Fixes #1275

## Mobile & Desktop Screenshots/Recordings

Screenshot 2023-06-22 at 11 00 43 AM

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by OgDev-01 — APPROVED** [review]
Thanks for this @codewithshariq! 
LGTM 🍕

**Comment by OgDev-01** [comment]
> @OgDev-01 there is another issue with the time format. The hour's value should not be greater than 11 in the case of "PM". Should I open a new issue to fix that or can I fix it within this PR as an additional improvement?

Since it's a tiny change, adding it here won't hurt 😇😇

File: lib/utils/timezones.ts [hunk 1]
```diff
@@ -1198,5 +1198,5 @@ export const getTimeByTimezone = (offset: number) => {
   // using supplied offset
   const time = new Date(utc + 3600000 * offset);
 
-  return `${time.getHours()}:${time.getMinutes()}${time.getHours() > 11 ? "pm" : "am"}`;
+  return `${time.getHours()}:${`0${time.getMinutes()}`.slice(-2)}${time.getHours() > 11 ? "pm" : "am"}`;
```
Comment (brandonroberts) [inline lib/utils/timezones.ts:1201]: Let's conditionally prefix the minutes instead of slicing after:

```suggestion
  return `${time.getHours()}:${`${time.getMinutes() < 10  ? "0" : ""}${time.getMinutes()}}${time.getHours() > 11 ? "pm" : "am"}`;
```

**Review by brandonroberts — CHANGES_REQUESTED** [review]

File: lib/utils/timezones.ts (hunk 1 above)
Comment (codewithshariq) [reply lib/utils/timezones.ts:1201]: How about using the format method form "date-fns" library? It is already installed as a dependency.

```
export const getTimeByTimezone = (offset: number) => {
  var d = new Date();

  // convert to msec
  // subtract local time zone offset
  // get UTC time in msec
  const utc = d.getTime() + d.getTimezoneOffset() * 60000;

  // create new Date object for different city
  // using supplied offset
  const time = new Date(utc + 3600000 * offset);

  return format(time, "hh:mmaaa");
};

```

Comment (brandonroberts) [reply lib/utils/timezones.ts:1201]: Yes, using date-fns would be more predictable for formatting

File: lib/utils/timezones.ts [hunk 2]
```diff
@@ -1198,5 +1200,5 @@ export const getTimeByTimezone = (offset: number) => {
   // using supplied offset
   const time = new Date(utc + 3600000 * offset);
 
-  return `${time.getHours()}:${time.getMinutes()}${time.getHours() > 11 ? "pm" : "am"}`;
+  return format(time, "hh:mmaaa");
```
Comment (NsdHSO) [inline lib/utils/timezones.ts:1203]:
```suggestion
  // The formatted time in the specified timezone
  return format(time, "hh:mmaaa");
```

**Review by NsdHSO — COMMENTED** [review]
LGTM

**Review by brandonroberts — APPROVED** [review]
