### PR TITLE
fix: improve layout design for large screens #1231

### LINKED ISSUE #1231: Feature: Odd design for large screens
### Type of feature

🎨 Style

### Current behavior

When you are on large screen, the add to insights button and the table collabse.
image
a 

### Suggested solution

It would be great to keep the button visible 

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by RitaDee**
## Description

This PR fixes the issue of Odd design for large screens #1231

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents 

-  Fixes #1231.

## Desktop Screenshots:

**Before**:

8C5F2307-292D-44E7-A443-6E758D5093BD_1_105_c

**After**:

C96D37BA-D979-499E-BEF9-1AEBF06638EF

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
Screen cap before and after please

**Comment by RitaDee** [comment]
@bdougie, done. Thank you but it is yet to pass the checks

File: components/organisms/Repositories/repositories.tsx [hunk 1]
```diff
@@ -90,6 +90,14 @@ const Repositories = ({ repositories }: RepositoriesProps): JSX.Element => {
...
   }, [selectedFilter, setPage]);
 
+  const containerStyles = {
+    minWidth: "90%", // Adjust the value as needed for smaller screens
+  };
+
+  const smallScreenStyles = {
+    minWidth: "100%", // Set the width to occupy the full screen for mobile devices
+  };
+
```
Comment (OgDev-01) [inline components/organisms/Repositories/repositories.tsx:100]: You don't need this... you can use tailwinds equivalent 

`w-11/12` and `w-full` 
check [tailwinds cheet sheet](https://flowbite.com/tools/tailwind-cheat-sheet/) for more utils

**Review by OgDev-01 — CHANGES_REQUESTED** [review]

File: components/organisms/Repositories/repositories.tsx (hunk 1 above)
Comment (RitaDee) [reply components/organisms/Repositories/repositories.tsx:100]: Thank you for the review, @OgDev-01 

I will implement the stated changes.

**Comment by RitaDee** [comment]
Closing this as the solution seems a little scope crept to me 😊🫠!

**Comment by a0m0rajab** [comment]
@RitaDee if you want to keep working on this and get some help, I would be more than happy to walk through with you in this PR. 

It might be worth taking a look at these codes if you are still interested. 

https://github.com/open-sauced/insights/blob/932568ffe78b810b68fa0f053e62c87f7f9ceb9d/components/molecules/RepoRow/repo-row.tsx#L191-L200

https://github.com/open-sauced/insights/blob/932568ffe78b810b68fa0f053e62c87f7f9ceb9d/components/molecules/RepoRow/repo-row.tsx#L263-L268

**Comment by RitaDee** [comment]
Hello @a0m0rajab, I will be glad to receive the walkthrough. Kindly let me know what time works best for you. Thank you

**Comment by a0m0rajab** [comment]
Awesome, to set expectations, this is a bit of a tricky task (you might need to change around 6-7 files till you get it fixed), there is a lot of complexity in it, and that's okay to find it hard, yet it's a bit of a great way to get familiar with the code. 

To implement this, you can do the next: 

- Get Identifier: go to the insight page, use your browser's page inspector, and get the related class/identifier of the item you want to change.
- Understand the code: After getting that identifier, you will need to check it from the code and see where it has been used, 
- Make changes: Since we checked the code, we will make some changes based on our knowledge to see if it works or not, 
- Review the changes: we need to review the changes and see how the result, and if there is anything else broken, 
- Repeat the steps: if there is anything broken and not working as expected, we need to redo the whole steps till we get the needed result. 

Each iteration will teach you about the code, the logic, and how it works. 

As for this task, 

## Get Identifier 

Here is how you can do this: 

https://github.com/open-sauced/insights/assets/18273833/b785542c-c531-490e-bee7-0cd54d3ab5da

From this at the end, you can see that I got; `flex-1 lg:min-w-[150px] hidden lg:flex`

I will go to my code editor right now or GitHub to find these classes. 

I am using VsCode so here is how to do it with it: 

https://github.com/open-sauced/insights/assets/18273833/189836d6-9963-47a8-9a4b-a08b52980557

Here is how to do it with GitHub: 
- open the repo page
- write the search term
- check the results 

https://github.com/open-sauced/insights/assets/18273833/b1825819-b19a-4261-b355-508786f7b05f

GitHub Result: 

https://github.com/search?q=repo%3Aopen-sauced%2Finsights%20flex-1%20lg%3Amin-w-%5B150px%5D%20hidden%20lg%3Aflex&type=code

## Understand the code

Since we got the related code right now, we will need to understand it. The first thing to notice is that it has a comment saying it's a column and it's using tailwind:

```js
 {/* Column Last 30 Days */}
        <div className={clsx("flex-1 lg:min-w-[150px] hidden lg:flex justify-center")}>
          {last30days ? <Sparkline data={last30days} width="100%" height={54} /> : "-"}
        </div>
```

https://github.com/open-sauced/insights/blob/932568ffe78b810b68fa0f053e62c87f7f9ceb9d/components/molecules/ContributorListTableRow/contributor-list-table-row.tsx#L171C1-L175


<details><summary>Tailwind</summary>
<p>

If you need to become more familiar with it, it's just a short style of writing CSS as a class. It has a special identifier as well. For example: 

`sm:m-50 lg:w-100`

The previous code is converting to: if small screen, then the width should be 50% if large screens, then the width is 100%

https://tailwindcss.com/docs/responsive-design

</p>
</details> 

We can see that the keyword hidden is being used as well. Here we can have three questions: 
- what would happen if we removed hidden? 
- When is it hidden, and when it's shown? 
- How to hide it on the screen that I want

## Make changes

Since we get that, we can now change the code and see the results. We can change the `lg` to `xl` since we want to hide the things in the large screen and see the result, if it is okay we can move forward. 

## The result

After doing changes in code, you need to run it on your local machine to test it, get the screen, and see if you need to fix/change anything else.

## Repeat 

You can repeat the same steps for a 4-5 times till you get the full expected result, again this is a bit tricky task though.


If you need any help or if you feel stuck and like to pair program then I would be happy to do that on discord: contributors channel.

**Comment by RitaDee** [comment]
Thank you, @a0m0rajab I will check it out.

**Comment by a0m0rajab** [comment]
I just had a 30-40 minutes call with @RitaDee to apply the https://github.com/open-sauced/insights/pull/1437/commits/d1d76f10bc36bc9404318f2fa5796985b45b185a commit. 

Thank you for your time! 

As for my opinion, I think that this PR is good right now but, I have two things in consideration: 
- the feed is a bit out of the scope of the issue 
- there are some changes that is a bit confusing for review.

File: components/organisms/Repositories/repositories.tsx
Comment (a0m0rajab) [inline components/organisms/Repositories/repositories.tsx:1]: The changes in this file is a bit confusing, from my perspective it could have a more clear changes.

**Comment by a0m0rajab** [comment]
This is how it looks right now: 
image

**Review by a0m0rajab — APPROVED** [review]
@RitaDee Thank you for your effort and force pushing the PR,

LGTM! 👍

**Comment by OgDev-01** [comment]
Testing this now and i can still see the issue exists cc: @RitaDee and @a0m0rajab 
https://github.com/open-sauced/insights/assets/62995161/164241f9-ffb5-4eff-ada4-3206a2f96446

**Comment by a0m0rajab** [comment]
@OgDev-01 the thing you are mentioning is a bit out of scope for this PR, you can check the issue: https://github.com/open-sauced/insights/issues/1231

The screenshot is a bit misleading

**Comment by OgDev-01** [comment]
> @OgDev-01 the thing you are mentioning is a bit out of scope for this PR, you can check the issue: #1231
> 
> The screenshot is a bit misleading

Thanks, I already deleted that... sorry about the misconceptions >:

**Review by OgDev-01 — APPROVED** [review]
LGTM 🍕 🍕 ... Thanks for this fix @RitaDee. Welcome to the community 👏

**Review by brandonroberts — APPROVED** [review]
🍕
